services:
  # --- INFRASTRUCTURE ---
  - type: worker
    name: medibook-db
    runtime: docker
    dockerContext: .
    dockerfilePath: ./mysql.Dockerfile
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: medibook_db

  - type: redis
    name: medibook-redis
    ipAllowList: [] 

  # --- CORE SERVICES ---
  - type: web
    name: eureka-server
    runtime: docker
    dockerContext: ./eureka-server
    envVars:
      - key: PORT
        value: 8761
      - key: JAVA_OPTS
        value: -Xmx192m -Xms128m

  - type: web
    name: auth-service
    runtime: docker
    dockerContext: ./auth-service
    envVars:
      - key: PORT
        value: 8081
      - key: JAVA_OPTS
        value: -Xmx256m -Xms128m
      - key: MYSQL_HOST
        fromService:
          name: medibook-db
          type: host
      - key: REDIS_HOST
        fromService:
          name: medibook-redis
          type: host
      - key: EUREKA_DEFAULT_ZONE
        value: http://eureka-server:8761/eureka
      - key: JWT_SECRET
        generateValue: true
      - key: INTERNAL_GATEWAY_SECRET
        generateValue: true

  - type: web
    name: api-gateway
    runtime: docker
    dockerContext: ./api-gateway
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Xmx256m -Xms128m
      - key: EUREKA_DEFAULT_ZONE
        value: http://eureka-server:8761/eureka
      - key: INTERNAL_GATEWAY_SECRET
        fromService:
          name: auth-service
          type: env
          key: INTERNAL_GATEWAY_SECRET
