sonar.projectKey=MediBook
sonar.projectName=MediBook
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=\
  api-gateway/target/site/jacoco/jacoco.xml,\
  appointment-service/target/site/jacoco/jacoco.xml,\
  auth-service/target/site/jacoco/jacoco.xml,\
  eureka-server/target/site/jacoco/jacoco.xml,\
  notification-service/target/site/jacoco/jacoco.xml,\
  payment-service/target/site/jacoco/jacoco.xml,\
  provider-service/target/site/jacoco/jacoco.xml,\
  record-service/target/site/jacoco/jacoco.xml,\
  review-service/target/site/jacoco/jacoco.xml,\
  schedule-service/target/site/jacoco/jacoco.xml
sonar.java.binaries=**/target/classes
