server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    name: ${LOG_FILE:../logs/${spring.application.name}.log}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
